theme: jekyll-theme-minimal
title: UCL Pharmacoepi Data Collaborative Online Knowledge Hub
description: Online learning and codesharing resource for pharmacoepidemiology using secondary datasets
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include: README.md
